name: Publish To NPM
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    name: "Build and publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-version
        run: |
          sudo apt install jq -y;
          echo "version=$(cat package.json | jq .version -j)" >> ${GITHUB_OUTPUT};
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - run: pnpm install --frozen-lockfile
      - name: publish
        if: ${{ github.event_name == 'workflow_dispatch' || steps.get-version.outputs.version == github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish
